fun main(args: Array<String>) {
    //Solve1().main()
    //Solve2().main()
    //Sovle3().main()
    //Solve4().main()
    //Solve5().main()
    //Solve6().main()
    //Solve7().main()
    //Solve8().main()
    //Solve9().main()
    //Solve10().main()
    //Solve11().main()
    //Solve12().main()
    //Solve13().main()
    //Solve14().main()
    //Solve16().main()
     Solve17().main()
    //TODO Solve18().main()
}